 </div><!-- close container -->
 <footer class="credits" id="credits">
            <h2>Credits</h2>
            <ul id="footer-ul">
                <li>Copyright &copy; 2017 - This webpage is created by Team Juneau</li>
                <li>Source materials for information sections are taken from <a href="http://www.rochester.edu/dining/learn-more/about-us/" target="_blank">U of R Dining Services</a></li>
                <li>This site is a revision of Team Juneau's Assignment 8: <a href="http://urcsc174.org/juneau/assignment8/survey.html" target="_blank">See Previous Version</a></li>
                <li>This site uses a plain vanilla login system provided by Robert Kostin.</li>
                <li>Authors: Daniella Bloom, Michelle Bushoy, Jerry Dai, Philip Kallinos</li>
                <li><a href="login.php">Admin Login/Signup</a></li>
            </ul>    
        </footer>
        
